version: '3.3'

services:
  database:
    image: mysql:5.6
    container_name: finance-app-database
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: finance
    expose:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci --init-connect='SET collation_connection = utf8mb4_unicode_520_ci; SET NAMES utf8mb4;'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  backend:
    container_name: finance-app-backend
    build:
      context: .
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
    volumes:
      - .:/opt/project
    ports:
      - "8000:8000"
    command: runserver
    restart: always
    depends_on:
      database:
        condition: service_healthy
